### PR TITLE
Add chain

### PR DESCRIPTION
**Pull request by SamiKammoun**
ask wallet to change current active chain or add a new chain

### CODE REVIEW

**Comment by ecp4224** [comment]
What wallets have you tested this with? From past experience I know the RPC method added has limited support by wallets

**Comment by SamiKammoun** [comment]
I only tried it with metamask, no idea if it works on other wallets. 
I did a small research just now and discovered that this method cannot be used for ethereum mainnet due to security considerations. (didn't try tho)
Also, switching networks was possible using this method although there's ` wallet_switchEthereumChain` that can be used instead.
What are your thoughts, what should I add/test ?

**Review by ecp4224 — APPROVED** [review]
After looking at the MetaMask mobile source, I can confirm these (previously unsupported) RPC methods are now supported (along with some new ones!)

[Source](https://github.com/MetaMask/metamask-mobile/blob/main/app/core/WalletConnect.js#L23)

I think this PR is good as is, however another PR should be opened to add the other RPC method for switching. This PR should also be merged with the Core library

**Comment by SamiKammoun** [comment]
Added method to switch chain, but lacks something.
An error.code `4092` should be emitted when the wallet doesn't have the requested chain and only in that case we can call `wallet_addEthereumChain`. How do I check the error code ?

**Pull request merged**
